name: Create Release and Upload Assets

on:
  push:
    tags:
      - 'v*' # Trigger only on tags that start with 'v'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt' # Specify the distribution here

      - name: Build with Maven
        run: mvn clean package


      # Only create a release if we have a tagged push
      - name: Release ${{ github.ref_type }} - ${{ github.ref_name }}
        if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            target/scanoss-*.jar